/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockdisplay_stuff.h"

static const char* CMockString_ask_for_student_data = "ask_for_student_data";
static const char* CMockString_student = "student";

typedef struct _CMOCK_ask_for_student_data_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  student_t* Expected_student;

} CMOCK_ask_for_student_data_CALL_INSTANCE;

static struct Mockdisplay_stuffInstance
{
  char ask_for_student_data_CallbackBool;
  CMOCK_ask_for_student_data_CALLBACK ask_for_student_data_CallbackFunctionPointer;
  int ask_for_student_data_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE ask_for_student_data_CallInstance;
} Mock;


void Mockdisplay_stuff_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.ask_for_student_data_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_ask_for_student_data);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.ask_for_student_data_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockdisplay_stuff_Init(void)
{
  Mockdisplay_stuff_Destroy();
}

void Mockdisplay_stuff_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void ask_for_student_data(student_t* student)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_ask_for_student_data_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_ask_for_student_data);
  cmock_call_instance = (CMOCK_ask_for_student_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ask_for_student_data_CallInstance);
  Mock.ask_for_student_data_CallInstance = CMock_Guts_MemNext(Mock.ask_for_student_data_CallInstance);
  if (!Mock.ask_for_student_data_CallbackBool &&
      Mock.ask_for_student_data_CallbackFunctionPointer != NULL)
  {
    Mock.ask_for_student_data_CallbackFunctionPointer(student, Mock.ask_for_student_data_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_ask_for_student_data,CMockString_student);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_student), (void*)(student), sizeof(student_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.ask_for_student_data_CallbackFunctionPointer != NULL)
  {
    Mock.ask_for_student_data_CallbackFunctionPointer(student, Mock.ask_for_student_data_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_ask_for_student_data(CMOCK_ask_for_student_data_CALL_INSTANCE* cmock_call_instance, student_t* student);
void CMockExpectParameters_ask_for_student_data(CMOCK_ask_for_student_data_CALL_INSTANCE* cmock_call_instance, student_t* student)
{
  cmock_call_instance->Expected_student = student;
}

void ask_for_student_data_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ask_for_student_data_CALL_INSTANCE));
  CMOCK_ask_for_student_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_ask_for_student_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ask_for_student_data_CallInstance = CMock_Guts_MemChain(Mock.ask_for_student_data_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void ask_for_student_data_CMockExpect(UNITY_LINE_TYPE cmock_line, student_t* student)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ask_for_student_data_CALL_INSTANCE));
  CMOCK_ask_for_student_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_ask_for_student_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ask_for_student_data_CallInstance = CMock_Guts_MemChain(Mock.ask_for_student_data_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_ask_for_student_data(cmock_call_instance, student);
}

void ask_for_student_data_AddCallback(CMOCK_ask_for_student_data_CALLBACK Callback)
{
  Mock.ask_for_student_data_CallbackBool = (char)1;
  Mock.ask_for_student_data_CallbackFunctionPointer = Callback;
}

void ask_for_student_data_Stub(CMOCK_ask_for_student_data_CALLBACK Callback)
{
  Mock.ask_for_student_data_CallbackBool = (char)0;
  Mock.ask_for_student_data_CallbackFunctionPointer = Callback;
}

