/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKDISPLAY_STUFF_H
#define _MOCKDISPLAY_STUFF_H

#include "unity.h"
#include "display_stuff.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockdisplay_stuff_Init(void);
void Mockdisplay_stuff_Destroy(void);
void Mockdisplay_stuff_Verify(void);




#define ask_for_student_data_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("ask_for_student_data requires _ExpectAnyArgs (not AndReturn)");
#define ask_for_student_data_ExpectAnyArgs() ask_for_student_data_CMockExpectAnyArgs(__LINE__)
void ask_for_student_data_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define ask_for_student_data_ExpectAndReturn(student, cmock_retval) TEST_FAIL_MESSAGE("ask_for_student_data requires _Expect (not AndReturn)");
#define ask_for_student_data_Expect(student) ask_for_student_data_CMockExpect(__LINE__, student)
void ask_for_student_data_CMockExpect(UNITY_LINE_TYPE cmock_line, student_t* student);
typedef void (* CMOCK_ask_for_student_data_CALLBACK)(student_t* student, int cmock_num_calls);
void ask_for_student_data_AddCallback(CMOCK_ask_for_student_data_CALLBACK Callback);
void ask_for_student_data_Stub(CMOCK_ask_for_student_data_CALLBACK Callback);
#define ask_for_student_data_StubWithCallback ask_for_student_data_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
