/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKFILE_HANDLING_H
#define _MOCKFILE_HANDLING_H

#include "unity.h"
#include "file_handling.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockfile_handling_Init(void);
void Mockfile_handling_Destroy(void);
void Mockfile_handling_Verify(void);




#define save_student_data_ExpectAnyArgs() TEST_FAIL_MESSAGE("save_student_data requires _ExpectAnyArgsAndReturn");
#define save_student_data_ExpectAnyArgsAndReturn(cmock_retval) save_student_data_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void save_student_data_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define save_student_data_Expect(student) TEST_FAIL_MESSAGE("save_student_data requires _ExpectAndReturn");
#define save_student_data_ExpectAndReturn(student, cmock_retval) save_student_data_CMockExpectAndReturn(__LINE__, student, cmock_retval)
void save_student_data_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, student_t* student, int cmock_to_return);
typedef int (* CMOCK_save_student_data_CALLBACK)(student_t* student, int cmock_num_calls);
void save_student_data_AddCallback(CMOCK_save_student_data_CALLBACK Callback);
void save_student_data_Stub(CMOCK_save_student_data_CALLBACK Callback);
#define save_student_data_StubWithCallback save_student_data_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
