/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockfile_handling.h"

static const char* CMockString_save_student_data = "save_student_data";
static const char* CMockString_student = "student";

typedef struct _CMOCK_save_student_data_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  student_t* Expected_student;

} CMOCK_save_student_data_CALL_INSTANCE;

static struct Mockfile_handlingInstance
{
  char save_student_data_CallbackBool;
  CMOCK_save_student_data_CALLBACK save_student_data_CallbackFunctionPointer;
  int save_student_data_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE save_student_data_CallInstance;
} Mock;


void Mockfile_handling_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.save_student_data_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_save_student_data);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.save_student_data_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockfile_handling_Init(void)
{
  Mockfile_handling_Destroy();
}

void Mockfile_handling_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int save_student_data(student_t* student)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_save_student_data_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_save_student_data);
  cmock_call_instance = (CMOCK_save_student_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.save_student_data_CallInstance);
  Mock.save_student_data_CallInstance = CMock_Guts_MemNext(Mock.save_student_data_CallInstance);
  if (!Mock.save_student_data_CallbackBool &&
      Mock.save_student_data_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.save_student_data_CallbackFunctionPointer(student, Mock.save_student_data_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_save_student_data,CMockString_student);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_student), (void*)(student), sizeof(student_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.save_student_data_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.save_student_data_CallbackFunctionPointer(student, Mock.save_student_data_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_save_student_data(CMOCK_save_student_data_CALL_INSTANCE* cmock_call_instance, student_t* student);
void CMockExpectParameters_save_student_data(CMOCK_save_student_data_CALL_INSTANCE* cmock_call_instance, student_t* student)
{
  cmock_call_instance->Expected_student = student;
}

void save_student_data_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_save_student_data_CALL_INSTANCE));
  CMOCK_save_student_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_save_student_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.save_student_data_CallInstance = CMock_Guts_MemChain(Mock.save_student_data_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void save_student_data_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, student_t* student, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_save_student_data_CALL_INSTANCE));
  CMOCK_save_student_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_save_student_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.save_student_data_CallInstance = CMock_Guts_MemChain(Mock.save_student_data_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_save_student_data(cmock_call_instance, student);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void save_student_data_AddCallback(CMOCK_save_student_data_CALLBACK Callback)
{
  Mock.save_student_data_CallbackBool = (char)1;
  Mock.save_student_data_CallbackFunctionPointer = Callback;
}

void save_student_data_Stub(CMOCK_save_student_data_CALLBACK Callback)
{
  Mock.save_student_data_CallbackBool = (char)0;
  Mock.save_student_data_CallbackFunctionPointer = Callback;
}

